ALTER TABLE People
DROP CONSTRAINT PK_IdUsername

ALTER TABLE People
ADD CONSTRAINT PK_UserId
PRIMARY KEY (Id)

ALTER TABLE People
ADD CONSTRAINT UK_Username
UNIQUE (Username)

ALTER TABLE People
ADD CONSTRAINT MinUsernameLength
CHECK (LEN(Username)>=3)